# Generated by Django 4.2.30 on 2026-04-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='ems_event_status_b6dfd7_idx',
            old_name='ems_event_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='ems_event_categor_d597a1_idx',
            old_name='ems_event_category_idx',
        ),
        migrations.RenameIndex(
            model_name='registration',
            new_name='ems_registr_status_6ae535_idx',
            old_name='ems_registration_status_idx',
        ),
        migrations.RenameIndex(
            model_name='registration',
            new_name='ems_registr_registe_e49a72_idx',
            old_name='ems_registration_date_idx',
        ),
    ]
